question_data = [
{"text": "Understanding basic SEO principles is essential for all content creation roles.", "answer": "True"},
{"text": "In Agile project management, work is typically divided into several phases with strict boundaries.", "answer": "False"},
{"text": "Data encryption is a recommended practice for securing sensitive information.", "answer": "True"},
{"text": "Cloud computing services eliminate the need for physical data storage on-site.", "answer": "True"},
{"text": "User experience (UX) design principles do not apply to internal company software tools.", "answer": "False"},
{"text": "A '404 error' indicates that a website is temporarily down for maintenance.", "answer": "False"},
{"text": "In object-oriented programming, 'inheritance' allows a class to use methods and properties of another class.", "answer": "True"},
{"text": "A strong password should include a mix of letters, numbers, and special characters.", "answer": "True"},
{"text": "Big Data analysis is only useful for large corporations and has no application in small businesses.", "answer": "False"},
{"text": "Continuous Integration and Continuous Deployment (CI/CD) are practices that apply only to software development.", "answer": "False"},
{"text": "Constructive criticism should be avoided as it may demotivate team members.", "answer": "False"},
{"text": "Effective teamwork requires every team member to agree on all decisions.", "answer": "False"},
{"text": "In conflict situations, finding a compromise is always the best solution.", "answer": "False"},
{"text": "Taking initiative on projects without being asked demonstrates leadership potential.", "answer": "True"},
{"text": "Employees should not seek feedback unless it is offered by their supervisors.", "answer": "False"},
{"text": "Admitting you do not know the answer to a question undermines your credibility.", "answer": "False"},
{"text": "Time management skills are crucial for roles that involve multitasking.", "answer": "True"},
{"text": "Remote work can never be as productive as working from an office.", "answer": "False"},
{"text": "It's important to maintain professional boundaries in all workplace communications.", "answer": "True"},
{"text": "Showing empathy towards colleagues can improve work relationships.", "answer": "True"},
{"text": "A flat organizational structure means decisions are only made by top management.", "answer": "False"},
{"text": "Workplace diversity includes a variety of perspectives, including educational backgrounds and work experience.", "answer": "True"},
{"text": "Companies should prioritize client satisfaction over employee well-being.", "answer": "False"},
{"text": "Sustainable practices are an integral part of modern business ethics.", "answer": "True"},
{"text": "A strong company culture relies on strict adherence to rules and policies.", "answer": "False"},
{"text": "Feedback loops are essential for continuous improvement in products and services.", "answer": "True"},
{"text": "Work-life balance should be the sole responsibility of the employee.", "answer": "False"},
{"text": "Mentorship programs within companies are beneficial only for new employees.", "answer": "False"},
{"text": "Open-door policies can encourage transparency and trust within an organization.", "answer": "True"},
{"text": "Innovation is the responsibility of specific departments, like R&D, rather than a company-wide effort.", "answer": "False"},
{"text": "Seeking roles with increasing responsibility demonstrates ambition and career growth.", "answer": "True"},
{"text": "Being content with your current role and responsibilities indicates a lack of ambition.", "answer": "False"},
{"text": "Employees should have clear career goals and communicate them to their managers.", "answer": "True"},
{"text": "A good career path involves moving to different companies every few years to gain diverse experiences.", "answer": "False"},
{"text": "Professional development opportunities are essential for job satisfaction.", "answer": "True"},
{"text": "It's important to align personal values with the company's mission and vision.", "answer": "True"},
{"text": "Having a mentor is beneficial only at the early stages of one's career.", "answer": "False"},
{"text": "Career success is solely determined by one's professional achievements and promotions.", "answer": "False"},
{"text": "Workplace happiness is as important as salary in choosing a job.", "answer": "True"},
{"text": "Changing career paths is a risky move that should be avoided.", "answer": "False"},
{"text": "Job satisfaction directly impacts productivity and work quality.", "answer": "True"},
{"text": "It's acceptable to bypass standard procedures if it leads to a successful project outcome.", "answer": "False"},
{"text": "Confidentiality agreements are unnecessary in a trust-based work environment.", "answer": "False"},
{"text": "Team meetings are an effective way to ensure all members are aligned with project goals.", "answer": "True"},
{"text": "Taking breaks during work can decrease overall productivity.", "answer": "False"},
{"text": "Networking within the industry is important only for those in sales or marketing roles.", "answer": "False"},
{"text": "Personal projects and hobbies are irrelevant to professional development.", "answer": "False"},
{"text": "Only managers need to have good communication skills.", "answer": "False"},
{"text": "Feedback should always be positive to avoid demotivating employees.", "answer": "False"},
{"text": "A good leader makes decisions quickly, without consulting the team.", "answer": "False"},

]
